[project]
name = "code-ast-symbol-classifier"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Elif", email = "elifimil77@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "scikit-learn>=1.9.0",
]

[project.scripts]
code-ast-symbol-classifier = "code_ast_symbol_classifier:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
